# Generated by Django 4.1 on 2022-09-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contacts',
            field=models.CharField(help_text='Номер или соц. сеть', max_length=255),
        ),
    ]
