# Generated by Django 4.1 on 2022-08-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_orders_bottle_order'),
        ('client', '0004_rename_order_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
