# Generated by Django 4.1 on 2022-08-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bottle_alter_order_options_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='volume',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='bottles_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
