# Generated by Django 4.1 on 2022-08-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_user'),
        ('core', '0007_remove_bottle_address_bottle_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('bottle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count', to='client.orders')),
            ],
        ),
    ]
