# Generated by Django 4.1 on 2022-08-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_order_bottle_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='Orders',
            new_name='Order',
        ),
    ]
