# Generated by Django 4.1 on 2022-08-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_orders_order'),
        ('core', '0010_rename_orders_bottle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='Order',
            field=models.ManyToManyField(related_name='bottles', to='client.order', verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='bottlecount',
            name='bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count', to='core.bottle'),
        ),
    ]
