# Generated by Django 4.1 on 2022-08-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_orders_order'),
        ('core', '0012_bottlecount_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='Order',
        ),
        migrations.AddField(
            model_name='bottle',
            name='Orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='client.order', verbose_name='Заказы'),
        ),
    ]
