# Generated by Django 4.1 on 2022-08-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_bottle_order_bottle_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlecount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottlecount',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
