# Generated by Django 4.1 on 2022-08-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_order_client'),
        ('core', '0015_remove_bottle_orders_bottle_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='Order',
        ),
        migrations.AddField(
            model_name='bottle',
            name='Orders',
            field=models.ManyToManyField(related_name='bottles', to='client.order', verbose_name='Заказы'),
        ),
    ]
