# Generated by Django 4.1 on 2022-08-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_order_client'),
        ('core', '0016_remove_bottle_order_bottle_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='Orders',
        ),
        migrations.RemoveField(
            model_name='bottlecount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bottlecount',
            name='expired',
        ),
        migrations.AddField(
            model_name='bottlecount',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bottlecount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.order'),
        ),
    ]
