# Generated by Django 4.1 on 2022-08-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_bottle_orders_remove_bottlecount_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottlecount',
            old_name='order',
            new_name='order1',
        ),
    ]
