# Generated by Django 4.1 on 2022-08-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_order_client'),
        ('core', '0019_alter_bottlecount_order1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='client.order', verbose_name='Orders'),
        ),
    ]
